### ISSUE TITLE
things to look at.

### ISSUE THREAD

**Issue by Belook12** [Hankypoo7/Blooket-hacks-Hankypoo7-#17]
GO AWAY @belook12

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 delete this repo right now! All of  this code is Gliz's code also remove me as a contribuator.

-Snow

**Comment by Snowflake-Coder-H2o** [comment]
@Belook12 Should I delete all of this?


-Snow

**Comment by kgsensei** [comment]
Stop, It's not funny. These are empty threats and you're starting something that won't end well.

**Comment by kgsensei** [comment]
@Belook12 and now you too ig.

**Comment by kgsensei** [comment]
> @Hankypoo7 delete this repo right now! All of  this code is Gliz's code.
> 
> -Snow

It's literally github. Everything is open source. It's gonna be hard to threaten that someone took someone else's code. It happens to everyone. Just learn to deal with it.

**Comment by Snowflake-Coder-H2o** [comment]
@kgsensei Wait this isnt glz code?

**Comment by Snowflake-Coder-H2o** [comment]
@kgsensei Becuase I deleted a whole entire repo.

**Comment by kgsensei** [comment]
@Snowflake-Coder-H2o It might be gliz's code but there is no way to prove it definitively. There is no point in arguing about if code was stolen or not. Some of my code gets stolen like every day.

**Comment by Snowflake-Coder-H2o** [comment]
@Butchr666 ??

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Dont delete anything.

**Comment by Belook12** [comment]
this is his code, he can prove it.

**Comment by kgsensei** [comment]
> this is his code, he can prove it.

Awesome, doesn't matter.

**Comment by Hankypoo7** [comment]
hi guys im back from vacation lol sorry i wasnt here

**Comment by colbymcdaniel** [comment]
hello guys

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Dont worry about whats been happening

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 I had to delete my repo. So I will be copying some of your hacks until I code my own again. 


-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o what have yall been doing lately I had no internet.

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel i dont really know. I have been dealing with legal matters. I guess somehow I stole gliz's code. Even though I coded all of that myself and with @zasticbraydn

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o ok well did he say that h has proof about this acusation. if soi need some informtion and i mite be able to turn the tables.

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel dont worry about it.

**Comment by colbymcdaniel** [comment]
ok

**Comment by Hankypoo7** [comment]
hi i cant talk rn im in class be back in half hour but thanks guys

**Comment by Belook12** [comment]
This is a copyright of gliz work and he just confirmed it. You are removing his credits and are using the same code.

Talk to him at https://discord.gg/6VQawGjv gliz#0777 hes not accepting peoples friend request so join his discord server and talk to him there.

**Comment by kgsensei** [comment]
The plot thickens. Hey @Belook12 can you stop being an enforcer? If gliz has an issue with this, he should be the one to enforce it. Not one of his followers and/or stans. Unless you can prove to be in communication with gliz as a business associate then I would encourage everyone to ignore @Belook12. With this being said, if you are a business associate with gliz that would look really bad for him as you have been harassing random people online for a few days now.

Actually, I wouldn't have gotten involved at all if you didn't post false information on my own Blooket repo. While there may be a point, and some legal ground, to the issue here that doesn't justify some of the other things that you have done, for example, spreading false claims and openly advertising other repositories. All of the claims that you have made here can be countered legally by the actions you have taken elsewhere, all being completely unprovoked.

Fun fact, if you decide to keep spreading false information and harassing people then there could be legitimate legal actions taken against you. I'd advise that you stand down and let gliz handle all forward interactions himself as I have been in contact with them before and know that they will handle this in a much more civilized manner.

Thanks for your attention.

**Comment by Hankypoo7** [comment]
@kgsensei i appriciate you bro i got ainxiety and am thankful i dont have to deal with dumb stuff like this, thank you for making my day by standing up for me and showing that someone cares

**Comment by Hankypoo7** [comment]
> This is a copyright of gliz work and he just confirmed it. You are removing his credits and are using the same code.
> 
> Talk to him at https://discord.gg/6VQawGjv gliz#0777 hes not accepting peoples friend request so join his discord server and talk to him there.

also btw snowflake and zastic braydin coded it

**Comment by Snowflake-Coder-H2o** [comment]
@kgsensei Thank you bro so much. You just made my complete day. You just helped us out so much. I appreciate you so much no words can describe how thankful I am that you just did that huge essay. I just had a lot of anxiety reading what @Belook12 has been saying. @kgsensei I also thought that I was going to get into trouble with legal things, so I had to delete my blooket hack repo. So I deleted it. I don't know how to get it back. and Zastix won't message me back on Github. Again thank you so much @kgsensei

**Comment by kgsensei** [comment]
I reached out to gliz and it is copyrighted and licensed so as long as you don't copy his work then your perfectly fine.

If you do the about half of the legal threats are valid. Still not all of them though.

**Comment by Hankypoo7** [comment]
ok

**Comment by Snowflake-Coder-H2o** [comment]
@kgsensei But I coded alot of the hacks. using @zasticbraydn blooket hacks thing. So some of the hacks might be his.

**Comment by Snowflake-Coder-H2o** [comment]
@kgsensei @Belook12 @colbymcdaniel @Hankypoo7 I will now be closing this.
