### ISSUE TITLE
Schoolcheats ip loggers

### ISSUE THREAD

**Issue by Tech219** [Hankypoo7/Blooket-hacks-Hankypoo7-#85]
Recently someone was able to make the code avaible to see or "Decode obfuscated JavaScript" which is what the code is I believe, and it has ip loggers, and a bunch of people have seen this and known about it now. What scripts are associated with schoolcheats?

**Comment by TheVillainCoder** [comment]
@Tech219 Hello! This is something I have heard about but not confirmed. Is there a screenshot/proof you could send of this?

**Comment by isthatyourfaceoryouassicanttell** [comment]
what happened to hank?...

**Comment by VillainsRule4000** [comment]
@isthatyourfaceoryouassicanttell NO RICKROLLS! Also, @Hankypoo7 is less active (but I am here most of the day).

**Comment by Hankypoo7** [comment]
im here

**Comment by VillainsRule4000** [comment]
@Tech219 I don't exactly know, looking into it. Spam Boxes/Add Tokens has the Gliz credit. I don't know about others. There are apps that prevent your IP from being logged.

**Comment by Hankypoo7** [comment]
@VillainsRule4000 should I be concerned about this?

**Comment by VillainsRule4000** [comment]
@Hankypoo7 IDK. Oorwlly (Blooktuber) and a few other Blooket figures have said the same thing. Might be something to look into as hacks with IP loggers are BAD NEWS.

**Comment by Hankypoo7** [comment]
yeah

**Comment by Tech219** [comment]
yeah defo like ip loggers you can get ddosed just in a few clicks sheesh, you can get your address taken too soo 😬

**Comment by Snowflake-Coder-H2o** [comment]
@Tech219 We will look into this

**Comment by isthatyourfaceoryouassicanttell** [comment]
ok i got scared somebody else  took over

**Comment by Tech219** [comment]
Thinking about recoding these schoolcheats hacks since well. ip grabbers are no good. Idk though , I'll work on it and I'll provide details later

**Comment by VillainsRule4000** [comment]
@Tech219 If you would like to, I could work with you to make the hacks known.

**Comment by Tech219** [comment]
@VillainsRule4000 Alright sure.. go to my profile i have a schoolcheats respitory there, ill inv you

**Comment by Tech219** [comment]
https://github.com/Tech219/SCHOOLCHEATSHACKSFIX/invitations

**Comment by VillainsRule4000** [comment]
@Tech219 This one? https://github.com/Tech219/SCHOOLCHEATSHACKSFIX

**Comment by Tech219** [comment]
yeah

**Comment by Tech219** [comment]
@VillainsRule4000 yeah its that one, do u have discord? yeah the 0001 is spaces but dont use them

**Comment by VillainsRule4000** [comment]
@Tech219 no

**Comment by VillainsRule4000** [comment]
# IP LOGGERS
Every website you visit logs your IP address for some reason. Some common sites:
- weather.com - logs your IP to view your location to give you your weather
- Google - logs your IP to give you maps to places
- Blax/Betastar/Blacket - logs your IP to prevent alts.

None of these have malicious intent. Your IP isn't actually private.
Schoolcheats likely doesn't have malicious intent, otherwise they wouldn't say they log it in their [privacy policy](https://schoolcheats.net/privacy/#:~:text=and%20prevent%20fraud-,Log%20Files,-schoolcheats.net%20follows).
If you want to know how they use it, click the link above to visit the IP section of their policy.
Relax, people. There's always the [VPNs](https://chrome.google.com/webstore/detail/touch-vpn-secure-and-unli/bihmplhobchoageeokmgbdihknkjbknd?hl=en).
